version: '3.8'

services:
  filmoteka:
    image: filmoteka:latest
    build: ./
    command: ./wait_for_postgres.sh db go run cmd/main.go
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"